### ISSUE TITLE
Studio: Proton 8.0 has the same issues as Experimental

### ISSUE THREAD

**Issue by ThePandaParade** [WaviestBalloon/ApplejuiceCLI#21] opened 2024-02-05 16:08 UTC
As mentioned in #1 - Proton Experimental is currently broken due to changes done by Valve. However, changing to Proton 8.0 replicates the same issue.

On launching to an Experience, Studio instant crashes with ``BadWindow (invalid Window parameter)``. I have tried Proton Hotfix alongside Proton EAC Runtime, both replicate this issue as well.

I have also tried launching Studio from terminal, web and from the app menu itself - all provide the same issue.

Ran on Arch Linux x86_64. 

Config:
```json
{
  "global": {
    "cli": {},
    "config_version": "0",
    "misc": {
      "overrides": {
        "CHANNEL_DEPLOYMENT_CDN": null,
        "LATEST_VERSION_PLAYER_CHANNEL": null,
        "LATEST_VERSION_STUDIO_CHANNEL": null,
        "LIVE_DEPLOYMENT_CDN": null
      },
      "purge_cached_deployment_after_install": false
    },
    "ui": {}
  },
  "proton_installations": {
    "Proton - Experimental": "/home/robyndawn/.steam/steam/steamapps/common/Proton - Experimental",
    "Proton 8.0": "/home/robyndawn/.steam/steam/steamapps/common/Proton 8.0"
  },
  "roblox_installations": {
    "Player": {
      "channel": "LIVE",
      "configuration": {
        "enable_rpc": true,
        "parameters": "%command%",
        "preferred_compat": "proton"
      },
      "install_path": "/home/robyndawn/.local/share/applejuice/roblox/LIVE/Player/version-17f2f3d7fcfc48f5",
      "preferred_proton": "/home/robyndawn/.steam/steam/steamapps/common/Proton - Experimental",
      "version_hash": "version-17f2f3d7fcfc48f5"
    },
    "Studio": {
      "channel": "LIVE",
      "configuration": {
        "enable_rpc": true,
        "parameters": "%command%",
        "preferred_compat": "proton"
      },
      "install_path": "/home/robyndawn/.local/share/applejuice/roblox/LIVE/Studio/version-4db4dbde9ef74270",
      "preferred_proton": "/home/robyndawn/.steam/steam/steamapps/common/Proton 8.0",
      "version_hash": "version-4db4dbde9ef74270"
    }
  }
}
```

**Comment by WaviestBalloon** [comment] 2024-02-05 17:41
Can you provide video of the steps you took to launching Studio?

**Comment by ThePandaParade** [comment] 2024-02-05 17:45
> Can you provide video of the steps you took to launching Studio?

Sure can:

For terminal: running ``applejuicecli --launch --binary Studio``
For app menu: 
![image](https://github.com/WaviestBalloon/ApplejuiceCLI/assets/38332833/f83ca8a0-c67c-4fd5-93f0-3144b8aeafa6)
(I cant really explain much else there)
From website: create.roblox.com > (experience) > Edit on Studio

**Comment by WaviestBalloon** [comment] 2024-02-09 10:14
Quick update, another user is experiencing the same issue with Studio with Proton 8.0, even without going into any Baseplate game or published game on the same distribution.
Unfortunately this seems like is not fixable on our side and requires you to run Studio with Wine instead which Applejuice currently does not support yet.

What hardware are you running? If you could, provide a screenshot of `neofetch`, if you are using a Nvidia graphics cards please state if you are using proprietary drivers or not.

**Comment by ThePandaParade** [comment] 2024-02-17 18:17
damn talk about a late response lmao

From my knowledge this is the FOSS drivers.
![image](https://github.com/WaviestBalloon/ApplejuiceCLI/assets/38332833/c2cf9461-6c20-4ead-8145-cc71ebc788cb)

**Comment by WaviestBalloon** [comment] 2024-02-18 00:41
> From my knowledge this is the FOSS drivers.

Is Roblox running fine for you? I'm unsure if you are using Nouveau drivers (reverse engineered) or the recently open-sourced official Nvidia drivers.
Either way, another user has confirmed that Studio will not correctly run on their system both on Arch Linux and Linux Mint, I believe they had similar hardware configuration to your but I cannot say for sure.

Using Wine should fix the `BadWindow` Qt error, can you do the following: 
`WINEPREFIX=/home/robyndawn/.local/share/applejuice/prefixdata/pfx USER=steamuser wine ~/.local/share/applejuice/roblox/LIVE/Studio/version-2e9ec7d22bf54930/RobloxStudioBeta.exe`

If this does not work, replace `version-2e9ec7d22bf54930` to the newest version of Studio that is currently installed, you can check that by copying the `clientVersionUpload` entry from this endpoint: https://clientsettings.roblox.com/v2/client-version/WindowsStudio64/channel/LIVE

**Comment by WaviestBalloon** [comment] 2024-02-27 09:24
@ThePandaParade 
Studio seems to have had some sort of update which has significantly improved stability, please try again with the latest version of Proton and Studio.

**Comment by WaviestBalloon** [comment] 2024-04-19 14:02
Closing this Issue as no more information regarding the issue was given and recently I have figured out how to improve the stability of Studio under Wine.

**Closed** 2024-04-19 14:02 UTC
Labels: requires more info, won't/can't fix, Roblox-related issue/bug

**Comment by WaviestBalloon** [comment] 2024-04-19 14:05
> ~Studio seems to have had some sort of update which has significantly improved stability~, please try again with the latest version of Proton and Studio.

The reason why I stated that is, using the [`allow-diff-prefix-test` branch](https://github.com/WaviestBalloon/ApplejuiceCLI/tree/allow-diff-prefix-test) you can have two different prefixes for Player and Studio, it seems like Studio becomes unstable if placed under the same prefix as Player which is annoying.
I'll add the option to create separate prefixes in the rewrite. #20

**Comment by ThePandaParade** [comment] 2024-04-19 14:05
professional at not remembering to hit "reply"

Recent versions of Proton on both Studio and Player provide the error "Wine
is not supported.", this has been around since March. Will try again later
to see if this issue persists.

**Comment by WaviestBalloon** [comment] 2024-04-19 14:10
> professional at not remembering to hit "reply" Recent versions of Proton on both Studio and Player provide the error "Wine is not supported.", this has been around since March. Will try again later to see if this issue persists.

Launching Studio should not produce the Hyperion block message, you might be accidentally launching Player without knowing.

The Roblox web team recently made it so you cannot use the `create.roblox.com` workaround without changing your User-Agent on the website to a Windows-based one, so I would recommend installing the [`allow-diff-prefix-test` branch](https://github.com/WaviestBalloon/ApplejuiceCLI/tree/allow-diff-prefix-test) and appending `prefix` onto your `roblox_installations`, e.g.

```json
{
  "global": {
    ...
  },
  "proton_installations": {
    ...
  },
  "roblox_installations": {
    "Player": {
      ...
    },
    "Studio": {
      "channel": "LIVE",
      "configuration": {
        "enable_rpc": true,
        "parameters": "%command%",
        "preferred_compat": "proton"
      },
      "install_path": "/home/wav/.local/share/applejuice/roblox/LIVE/Studio/version-e2bc56a1e4374ca0",
      "preferred_proton": "Proton - Experimental",
      "version_hash": "version-e2bc56a1e4374ca0",
      "prefix": "studioprefix"
    }
  }
}
```
